version: '2.1'

services:
  hub:
    container_name: hub
    image: selenium/hub:2.53.1-beryllium
    ports:
     - '4444:4444'
    networks:
    - nightwatch

  firefox:
    container_name: firefox
    image: selenium/node-firefox:2.53.1-beryllium
    environment:
    - HUB_PORT_4444_TCP_ADDR=hub
    ports:
    - 9000
    depends_on:
    - app
    networks:
    - nightwatch

  chrome:
    container_name: chrome
    image: selenium/node-chrome:2.53.1-beryllium
    ports:
    - 9000
    environment:
    - HUB_PORT_4444_TCP_ADDR=hub
    depends_on:
    - app
    networks:
    - nightwatch

  app:
    container_name: app
    image: node:alpine
    environment:
    - HOST=0.0.0.0
    - PORT=4200
    - API='http://app:8080/api'
    ports:
    - '4200:4200'
    - '8080:8080'
    volumes:
    - ./:/ws
    working_dir: /ws/app
    entrypoint: /bin/sh -c 'npm install && npm run serve; tail -f /ws/app/package.json'
    networks:
    - nightwatch

  # e2e:
  #   container_name: e2e
  #   image: node:alpine
  #   environment:
  #   - BASE_URL='http://app:4200'
  #   ports:
  #   - '8080:8080'
  #   volumes:
  #   - ./:/ws
  #   working_dir: /ws/e2e
  #   entrypoint: /bin/sh -c 'npm install; tail -f /ws/e2e/package.json'
  #   networks:
  #   - nightwatch

volumes:
  data:
    name: nightwatch

networks:
  nightwatch:
    name: nightwatch
