version: '2.1'

services:
  seleniumhub:
    container_name: hub
    image: selenium/hub:2.53.1-beryllium
    ports:
      - "4444:4444"
    networks:
    - nightwatch

  firefoxnode:
    container_name: firefox
    image: selenium/node-firefox:2.53.1-beryllium
    environment:
    - HUB_PORT_4444_TCP_ADDR=seleniumhub
    ports:
    - 9000
    networks:
    - nightwatch

  chromenode:
    container_name: chrome
    image: selenium/node-chrome:2.53.1-beryllium
    ports:
      - 9000
    environment:
      - HUB_PORT_4444_TCP_ADDR=seleniumhub
    networks:
    - nightwatch

  nightwatch:
    container_name: nightwatch
    image: node:alpine
    volumes:
    - ./:/ws
    working_dir: /ws
    entrypoint: /bin/sh -c 'tail -f /ws/package.json'
    networks:
    - nightwatch

networks:
  nightwatch:
    name: nightwatch
